Vagrant.configure(2) do |config|

  config.vm.define "vSRX1" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX1"
    # ge 0/0/0
    srx.vm.network "private_network",
                    ip: "192.168.30.1"
    # ge 0/0/1
    srx.vm.network "private_network",
                    ip: "172.30.1.1"
    # ge 0/0/2
    srx.vm.network "private_network",
                    ip: "172.20.1.1"
    # ge 0/0/3
    srx.vm.network "private_network",
                    ip: "172.10.1.1"
    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX1"
      vb.cpus = 2
      vb.memory = 512
    end
  end

  config.vm.define "vSRX2" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX2"
    # ge 0/0/0
    srx.vm.network "private_network",
                    ip: "192.168.30.2"
    # ge 0/0/1
    srx.vm.network "private_network",
                    ip: "172.50.1.1"
    # ge 0/0/2
    srx.vm.network "private_network",
                    ip: "172.20.1.2"
    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX2"
      vb.cpus = 2
      vb.memory = 512
    end
  end

  config.vm.define "vSRX4" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX4"
    # ge 0/0/0
    srx.vm.network "private_network",
                    ip: "192.168.30.4"
    # ge 0/0/1
    srx.vm.network "private_network",
                    ip: "172.50.1.2"
    # ge 0/0/2
    srx.vm.network "private_network",
                    ip: "172.60.1.1"
    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX4"
      vb.cpus = 2
      vb.memory = 512
    end
  end

  config.vm.define "vSRX5" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX5"

    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX5"
      vb.cpus = 2
      vb.memory = 512
    end
  end

  config.vm.define "vSRX6" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX6"

    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX6"
      vb.cpus = 2
      vb.memory = 512
    end
  end

  config.vm.define "vSRX7" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D15.4"
    srx.vm.hostname = "vSRX7"

    srx.vm.provider "virtualbox" do |vb|
      vb.name = "project_network_vSRX7"
      vb.cpus = 2
      vb.memory = 512
    end

    config.vm.define "vMain" do |srx|
      srx.vm.box = "juniper/ffp-12.1X47-D15.4"
      srx.vm.hostname = "vMain"

      srx.vm.provider "virtualbox" do |vb|
        vb.name = "project_network_vMain"
        vb.cpus = 2
        vb.memory = 512
      end
    end

    config.vm.define "vOSPF" do |srx|
      srx.vm.box = "juniper/ffp-12.1X47-D15.4"
      srx.vm.hostname = "vOSPF"

      srx.vm.provider "virtualbox" do |vb|
        vb.name = "project_network_vOSPF"
        vb.cpus = 2
        vb.memory = 512
      end
    end

    config.vm.define "vOSPF2" do |srx|
      srx.vm.box = "juniper/ffp-12.1X47-D15.4"
      srx.vm.hostname = "vOSPF2"

      srx.vm.provider "virtualbox" do |vb|
        vb.name = "project_network_vOSPF2"
        vb.cpus = 2
        vb.memory = 512
      end
    end
  end
end
